apiVersion: batch/v1
kind: Job
metadata:
  name: testdatapy-correlated
  namespace: confluent
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: testdatapy-correlated
    spec:
      restartPolicy: Never
      containers:
      - name: testdatapy
        image: ghcr.io/ksilin/testdatapy:0.0.1
        imagePullPolicy: Always
        command:
        - python
        - /scripts/produce-correlated.py
        volumeMounts:
        - name: config
          mountPath: /config
        - name: scripts
          mountPath: /scripts
        - name: ca-cert-pem
          mountPath: /mnt/sslcerts/ca-pem
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: testdatapy-correlated-config
      - name: scripts
        configMap:
          name: testdatapy-scripts
      - name: ca-cert-pem
        secret:
          secretName: kafka-ca-cert-pem
