apiVersion: batch/v1
kind: Job
metadata:
  name: testdatapy-producer
  namespace: confluent
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: testdatapy
    spec:
      restartPolicy: Never
      containers:
      - name: testdatapy
        image: ghcr.io/ksilin/testdatapy:0.0.1
        imagePullPolicy: Always
        command:
        - testdatapy
        - produce
        - --config
        - /config/config.json
        - --topic
        - customers
        - --format
        - json
        - --generator
        - faker
        - --count
        - "1000"
        - --rate
        - "10"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: ca-cert-pem
          mountPath: /mnt/sslcerts/ca-pem
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: testdatapy-config
      - name: ca-cert-pem
        secret:
          secretName: kafka-ca-cert-pem
