version: '3'

services:

  # This extends the existing docker-compose.yml from testdatapy
  # It adds a new service for correlated data generation

  testdatapy-correlated:
    image: ghcr.io/ksilin/testdatapy:0.0.1
    container_name: testdatapy-correlated
    restart: "no"
    command: python /scripts/produce-correlated.py
    environment:
      - DOCKER_ENV=true
    volumes:
      - ./configs/kafka-config.json:/config/kafka-config.json
      - ./configs/ecommerce-correlated.yaml:/config/ecommerce-correlated.yaml
      - ./scripts/produce-correlated.py:/scripts/produce-correlated.py
    networks:
      - testdata-network

networks:
  testdata-network:
    external: true
