# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: delivery.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'delivery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x65livery.proto\x12\x14\x63om.example.protobuf\"\xd9\x04\n\x08\x44\x65livery\x12\x13\n\x0b\x64\x65livery_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x17\n\x0ftracking_number\x18\x03 \x01(\t\x12\x0f\n\x07\x63\x61rrier\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x14\n\x0cshipped_date\x18\x06 \x01(\t\x12\x1f\n\x17\x65stimated_delivery_date\x18\x07 \x01(\t\x12\x1c\n\x14\x61\x63tual_delivery_date\x18\x08 \x01(\t\x12H\n\x10\x64\x65livery_address\x18\t \x01(\x0b\x32..com.example.protobuf.Delivery.DeliveryAddress\x12\x45\n\x0ftracking_events\x18\n \x03(\x0b\x32,.com.example.protobuf.Delivery.TrackingEvent\x12\x12\n\ncreated_at\x18\x0b \x01(\t\x12\x12\n\nupdated_at\x18\x0c \x01(\t\x1a\x81\x01\n\x0f\x44\x65liveryAddress\x12\x16\n\x0erecipient_name\x18\x01 \x01(\t\x12\x0e\n\x06street\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\x13\n\x0bpostal_code\x18\x04 \x01(\t\x12\x14\n\x0c\x63ountry_code\x18\x05 \x01(\t\x12\r\n\x05phone\x18\x06 \x01(\t\x1aZ\n\rTrackingEvent\x12\x12\n\nevent_time\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'delivery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DELIVERY']._serialized_start=41
  _globals['_DELIVERY']._serialized_end=642
  _globals['_DELIVERY_DELIVERYADDRESS']._serialized_start=421
  _globals['_DELIVERY_DELIVERYADDRESS']._serialized_end=550
  _globals['_DELIVERY_TRACKINGEVENT']._serialized_start=552
  _globals['_DELIVERY_TRACKINGEVENT']._serialized_end=642
# @@protoc_insertion_point(module_scope)
