# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x14\x63om.example.protobuf\"\xb8\x04\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\t\x12\x12\n\norder_date\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12:\n\x0border_items\x18\x05 \x03(\x0b\x32%.com.example.protobuf.Order.OrderItem\x12\x10\n\x08subtotal\x18\x06 \x01(\x01\x12\x0b\n\x03tax\x18\x07 \x01(\x01\x12\x15\n\rshipping_cost\x18\x08 \x01(\x01\x12\x14\n\x0ctotal_amount\x18\t \x01(\x01\x12\x45\n\x10shipping_address\x18\n \x01(\x0b\x32+.com.example.protobuf.Order.ShippingAddress\x12\x12\n\ncreated_at\x18\x0b \x01(\t\x12\x12\n\nupdated_at\x18\x0c \x01(\t\x1ai\n\tOrderItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x12\n\nunit_price\x18\x03 \x01(\x01\x12\x10\n\x08\x64iscount\x18\x04 \x01(\x01\x12\x10\n\x08subtotal\x18\x05 \x01(\x01\x1a\x81\x01\n\x0fShippingAddress\x12\x16\n\x0erecipient_name\x18\x01 \x01(\t\x12\x0e\n\x06street\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\x13\n\x0bpostal_code\x18\x04 \x01(\t\x12\x14\n\x0c\x63ountry_code\x18\x05 \x01(\t\x12\r\n\x05phone\x18\x06 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=38
  _globals['_ORDER']._serialized_end=606
  _globals['_ORDER_ORDERITEM']._serialized_start=369
  _globals['_ORDER_ORDERITEM']._serialized_end=474
  _globals['_ORDER_SHIPPINGADDRESS']._serialized_start=477
  _globals['_ORDER_SHIPPINGADDRESS']._serialized_end=606
# @@protoc_insertion_point(module_scope)
