# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x14\x63om.example.protobuf\"\xb9\x03\n\x07Payment\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x03 \x01(\t\x12\x14\n\x0cpayment_date\x18\x04 \x01(\t\x12\x0e\n\x06\x61mount\x18\x05 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x06 \x01(\t\x12\x16\n\x0epayment_method\x18\x07 \x01(\t\x12\x0e\n\x06status\x18\x08 \x01(\t\x12>\n\x0b\x63redit_card\x18\t \x01(\x0b\x32\'.com.example.protobuf.CreditCardDetailsH\x00\x12\x42\n\rbank_transfer\x18\n \x01(\x0b\x32).com.example.protobuf.BankTransferDetailsH\x00\x12\x35\n\x06paypal\x18\x0b \x01(\x0b\x32#.com.example.protobuf.PayPalDetailsH\x00\x12\x1d\n\x15transaction_reference\x18\x0c \x01(\t\x12\x12\n\ncreated_at\x18\r \x01(\t\x12\x12\n\nupdated_at\x18\x0e \x01(\tB\x11\n\x0fpayment_details\"[\n\x11\x43reditCardDetails\x12\x18\n\x10last_four_digits\x18\x01 \x01(\t\x12\x12\n\ncard_brand\x18\x02 \x01(\t\x12\x18\n\x10\x63\x61rd_holder_name\x18\x03 \x01(\t\"_\n\x13\x42\x61nkTransferDetails\x12\x11\n\tbank_name\x18\x01 \x01(\t\x12\x1d\n\x15\x61\x63\x63ount_number_suffix\x18\x02 \x01(\t\x12\x16\n\x0erouting_number\x18\x03 \x01(\t\"D\n\rPayPalDetails\x12\x14\n\x0cpaypal_email\x18\x01 \x01(\t\x12\x1d\n\x15paypal_transaction_id\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYMENT']._serialized_start=40
  _globals['_PAYMENT']._serialized_end=481
  _globals['_CREDITCARDDETAILS']._serialized_start=483
  _globals['_CREDITCARDDETAILS']._serialized_end=574
  _globals['_BANKTRANSFERDETAILS']._serialized_start=576
  _globals['_BANKTRANSFERDETAILS']._serialized_end=671
  _globals['_PAYPALDETAILS']._serialized_start=673
  _globals['_PAYPALDETAILS']._serialized_end=741
# @@protoc_insertion_point(module_scope)
